Add support for 2024.3 symbol dictionaries
nvdaaddons/AddonTemplate pull request #43
Opened 2024-08-17 13:26 UTC by LeonarddeR

2024-08-17 17:38 UTC, nvdaes commented
Thanks so much @LeonarddeR . I was thinking about requesting this on the add-ons mailing list time ago,but then I started doing other things and I never requested it.
I use dictionaries in an add-on named Perky, for Perky  Duck, a program to learn braille. I'm not sure if this will be appropriate for the add-on, but I'll study it.

2024-08-17 22:47 UTC, nvdaes requested changes

2024-08-17 22:47 UTC, nvdaes commented on buildVars.py
> +# displayName (name of the table shown to users and translatable),
```suggestion
# displayName (name of the speech dictionary  shown to users and translatable),
```

2024-08-17 22:47 UTC, nvdaes commented on readme.md
> +###### SPeech symbol dictionaries
```suggestion
###### Speech symbol dictionaries
```

2024-08-29 13:59 UTC, josephsl approved these changes
Thank you for your contribution (and good luck in the next adventure).

2024-08-29 14:00 UTC, merged